/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Decimal = ColumnType<string, number | string>;

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Tbacc {
  acceso: number;
  activo: number;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  nomacceso: string;
  usumod: number;
  usunvo: number;
}

export interface Tbaccclases {
  accclase: number;
  acceso: number;
  activo: number;
  clase: number;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  usumod: number;
  usunvo: number;
}

export interface Tbaccesos {
  acceso: number;
  agregar: number;
  eliminar: number;
  envia: number;
  id: Generated<number>;
  imprimir: number;
  modificar: number;
  opcion: number;
  subopcion: number;
  usuario: number;
}

export interface Tbaccperfiles {
  acceso: number;
  agregar: number;
  eliminar: number;
  envia: number;
  id: Generated<number>;
  imprimir: number;
  modificar: number;
  opcion: number;
  perfil: number;
  subopcion: number;
}

export interface Tbagenda {
  correo: string;
  empleado: number;
  envia: Decimal;
  fecha: Date;
  fecmod: Date;
  fecnvo: Date;
  hora: number;
  horarioclase: Generated<number>;
  idagenda: Generated<number>;
  obs: string;
  precita: number;
  producto: number;
  sala: number;
  sesion: number;
  socio: number;
  tomada: Decimal;
  usumod: number;
  usunvo: number;
}

export interface Tbapertura {
  abrir: number;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  usumod: number;
  usunvo: number;
}

export interface Tbaperturas {
  envia: number;
  fecha: Date;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  motivo: string | null;
  usumod: number;
  usunvo: number;
}

export interface Tbasistencia {
  autorizo: number;
  clase: number;
  envia: number;
  fecha: Date;
  fecmod: Date;
  fecnvo: Date;
  horario: number;
  id: Generated<number>;
  instructor: number;
  motivo: string;
  retardo: number;
  socio: number;
  usumod: number;
  usunvo: number;
}

export interface Tbbancos {
  banco: Generated<number>;
  cuenta: string;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  nombanco: string;
  nombre: string;
  rfc: string;
  usumod: number;
  usunvo: number;
}

export interface Tbbdkpc {
  cerrar: number;
  enuso: number;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  hora: Date;
  minimizar: number;
  parapc: string;
  paraserver: string;
  tiempo: Decimal;
  usumod: number;
  usunvo: number;
}

export interface Tbbloqueados {
  activo: number;
  correobloq: string;
  envia: string;
  fecmod: Date;
  fecnvo: Date;
  id: number;
  usumod: number;
  usunvo: number;
}

export interface Tbcategorias {
  categoria: number;
  color: string;
  enpantalla: number;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  fotocat: string;
  id: Generated<number>;
  nomcategoria: string;
  principal: number;
  usumod: number;
  usunvo: number;
}

export interface TbcClaveprodser {
  c_claveprodserv: string;
  descripcion: string;
  envia: number;
  fecfinvig: Date;
  fecinivig: Date;
  fecmod: Date;
  fecnvo: Date;
  inclcompl: string;
  inclIEPStr: string;
  inclIVAtr: string;
  usumod: number;
  usunvo: number;
}

export interface TbcClaveunidad {
  c_claveunidad: string;
  descripcion: string;
  envia: number;
  fechafinvig: Date;
  fechainivig: Date;
  fecmod: Date;
  fecnvo: Date;
  nombre: string;
  simbolo: string;
  usumod: number;
  usunvo: number;
}

export interface TbcCodigopostal {
  c_codigopostal: string;
  c_estado: string;
  c_localidad: string;
  c_municipio: string;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  usumod: number;
  usunvo: number;
}

export interface Tbcfdis {
  cadenaor: string;
  certem: string;
  certsat: string;
  cfdirelacionado: string;
  envia: number;
  factura: number;
  fecmod: Date;
  fecnvo: Date;
  fectim: string;
  sello: string;
  selloem: string;
  serie: string;
  tipodecomprobante: string;
  tipoderelacion: number;
  usumod: number;
  usunvo: number;
  uuid: string;
}

export interface TbcFormapago {
  bancarizado: string;
  bco_emisor_cta_ord_extranjero: string;
  c_formapago: string;
  cta_benenficiario: string;
  cta_ordenante: string;
  descripcion: string;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  num_oper: string;
  pat_cta_beneficiario: string;
  patron_cta_ordenante: string;
  RFC_emisor_beneficiario: string;
  RFC_emisor_ordenante: string;
  tipo_cadena_pago: string;
  usumod: number;
  usunvo: number;
}

export interface Tbclases {
  activa: number;
  clase: number;
  cntlimite: number;
  cobinsc: number;
  controlhr: number;
  descanual: Decimal;
  descmes: Decimal;
  descqna: Decimal;
  descsem: Decimal;
  descstre: Decimal;
  desctrim: Decimal;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  impticketasist: number;
  limitectes: number;
  nomclase: string;
  pranual: Decimal;
  prinsc: Decimal;
  prmes: Decimal;
  prqna: Decimal;
  prsem: Decimal;
  prstre: Decimal;
  prtrim: Decimal;
  usumod: number;
  usunvo: number;
}

export interface TbcMetodopago {
  c_metodopago: string;
  descripcion: string;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  usumod: number;
  usunvo: number;
}

export interface TbcMoneda {
  c_moneda: string;
  decimales: string;
  descripcion: string;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  porcvar: string;
  usumod: number;
  usunvo: number;
}

export interface Tbcobranza {
  cancel: number;
  cliente: number;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  fecpag: Date;
  formapago: number;
  idfac: number;
  idpag: number;
  importe: Decimal;
  metodopago: string;
  moneda: Decimal;
  noparcialidad: number;
  pago: number;
  referencia: string;
  saldoant: Decimal;
  saldonvo: Decimal;
  tcambiodr: Decimal;
  tipocambio: Decimal;
  usumod: number;
  usunvo: number;
}

export interface Tbconceptos {
  concepto: number;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  nomconcepto: string;
  usumod: number;
  usunvo: number;
}

export interface Tbconsumodieta {
  activo: number;
  consumo: number;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  nomconsumo: string;
  usumod: number;
  usunvo: number;
}

export interface Tbcortes {
  bauchers: Decimal;
  cheques: Decimal;
  compras: Decimal;
  corte: number;
  efecencaja: Decimal;
  efectivo: Decimal;
  entradafin: number;
  entradaini: number;
  envia: number;
  faltante: Decimal;
  fdocaja: Decimal;
  fecha: Date;
  fecmod: Date;
  fecnvo: Date;
  fichasdep: Decimal;
  gastos: Decimal;
  id: Generated<number>;
  ingefec: Decimal;
  obs: string | null;
  salefec: Decimal;
  salidafin: number;
  salidaini: number;
  sobrante: Decimal;
  totingresos: Decimal;
  usuario: number;
  usumod: number;
  usunvo: number;
  vales: Decimal;
  vtascredito: Decimal;
}

export interface TbcRegimenfiscal {
  c_regimenfiscal: string;
  descripcion: string;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  pfisica: string;
  pmoral: string;
  usumod: number;
  usunvo: number;
}

export interface TbcTasaocuota {
  c_tasaocuotavmax: Decimal;
  c_tasaocuotavmin: string;
  envia: number;
  factor: string;
  fecmod: Date;
  fecnvo: Date;
  impuesto: string;
  rangoofijo: string;
  retencion: string;
  traslado: string;
  usumod: number;
  usunvo: number;
}

export interface TbcTipocadenapago {
  c_tipocadena: string;
  descripcion: string;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  usumod: number;
  usunvo: number;
}

export interface TbcTipocomprobante {
  c_tipocomprobante: string;
  descripcion: string;
  valormax: string;
}

export interface TbcTiporelacion {
  c_tiporelacion: string | null;
  descripcion: string | null;
  envia: number | null;
  fecfinvig: Date | null;
  fecinivig: Date | null;
  fecmod: Date | null;
  fecnvo: Date | null;
  usumod: number | null;
  usunvo: number | null;
}

export interface TbcUsocfdi {
  appfisica: string;
  appmoral: string;
  c_usoCFDI: string;
  descripcion: string;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  usumod: number;
  usunvo: number;
}

export interface Tbdescuentos {
  autdes: number;
  cancelado: number;
  corte: number;
  descuento: Decimal;
  envia: number;
  fecha: Date;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  iddesc: number;
  idmens: number;
  importe: Decimal;
  motivo: string;
  socio: number;
  ticket: number;
  total: Decimal;
  usuario: number;
  usumod: number;
  usunvo: number;
}

export interface Tbdetcortes {
  corte: number;
  descrip: string;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  importe: Decimal;
  nomsocio: string;
  subtit: number;
  tit: number;
  titulo: string;
  total: number;
  usumod: number;
  usunvo: number;
}

export interface Tbdetdietas {
  activo: number;
  alimentos: string;
  consumo: number;
  dia: number;
  dieta: number;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  usumod: number;
  usunvo: number;
}

export interface Tbdetdietasocio {
  activo: number;
  alimentos: string;
  consumo: number;
  dia: number;
  dieta: number;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  socio: number;
  usumod: number;
  usunvo: number;
}

export interface Tbdetentradasalm {
  cnt: Decimal;
  costo: Decimal;
  envia: number;
  exant: Decimal;
  exnva: Decimal;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  ident: number;
  idreg: number;
  producto: number;
  total: Decimal;
  usumod: number;
  usunvo: number;
  venta: Decimal;
}

export interface Tbdetfacs {
  baseieps1: Decimal;
  baseieps2: Decimal;
  baseieps3: Decimal;
  baseieps4: Decimal;
  baseieps5: Decimal;
  baseieps6: Decimal;
  baseiva: Decimal;
  claveunidad: string;
  cnt: Decimal;
  cveprodserv: string;
  descuento: Decimal;
  envia: number;
  factura: number;
  fechaventa: Date;
  fecmod: Date;
  fecnvo: Date;
  geniva: number;
  ieps: Decimal;
  ieps1: Decimal;
  ieps2: Decimal;
  ieps3: Decimal;
  ieps4: Decimal;
  ieps5: Decimal;
  ieps6: Decimal;
  importe: Decimal;
  iva: Decimal;
  nomproducto: string;
  porcieps: Decimal;
  PorcIEPS1: Decimal;
  PorcIEPS2: Decimal;
  porcieps3: Decimal;
  porcieps4: Decimal;
  porcieps5: Decimal;
  porcieps6: Decimal;
  producto: number;
  registro: number;
  serie: string;
  subtotal: Decimal;
  ticket: number;
  usumod: number;
  usunvo: number;
  venta: Decimal;
}

export interface Tbdetoc {
  cnt: Decimal;
  costo: Decimal;
  entregado: Decimal;
  envia: number;
  existencia: Decimal;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  idreg: number;
  oc: number;
  producto: number;
  total: Decimal;
  usumod: number;
  usunvo: number;
}

export interface Tbdetrutinasocio {
  activo: number;
  comentarios: string;
  descanso: string;
  dia: number;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  peso: string;
  repeticiones: string;
  rutina: number;
  series: string;
  socio: number;
  usumod: number;
  usunvo: number;
}

export interface Tbdetsalidasalm {
  cnt: Decimal;
  costo: Decimal;
  envia: number;
  exant: Decimal;
  exnva: Decimal;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  idreg: number;
  idsal: number;
  producto: number;
  total: Decimal;
  usumod: number;
  usunvo: number;
}

export interface Tbdettickets {
  almacen: number;
  autcp: number;
  campre: number;
  cancelado: number;
  cnt: Decimal;
  combo: number;
  corte: number;
  costo: Decimal;
  descuento: Decimal;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  geniva: number;
  id: Generated<number>;
  idreg: number;
  ieps: Decimal;
  importe: Decimal;
  iva: Decimal;
  motcp: string;
  nomotros: string;
  paqvisitas: number;
  plazocred: number;
  porcieps: Decimal;
  precioreal: Decimal;
  producto: number;
  ticket: number;
  usumod: number;
  usunvo: number;
  venta: Decimal;
  visitas: number;
}

export interface Tbdietas {
  activo: number;
  comentarios: string;
  dieta: number;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  nomdieta: string;
  tipo: number;
  usumod: number;
  usunvo: number;
}

export interface Tbentradasalm {
  descrip: string;
  envia: number;
  fecha: Date;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  ident: number;
  iva: Decimal;
  obs: string | null;
  oc: number;
  proveedor: number;
  referencia: string;
  subtotal: Decimal;
  total: Decimal;
  usumod: number;
  usunvo: number;
}

export interface Tbestatus {
  envia: string;
  estatus: number;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  nomestatus: string;
  tipo: number;
  usumod: number;
  usunvo: number;
}

export interface Tbeventos {
  descripcion: string;
  envia: Generated<number>;
  estatus: Generated<number>;
  fecha: Date;
  fecmod: Date | null;
  fecnvo: Date | null;
  hora: string;
  idevento: Generated<number>;
  imagen: string;
  nombre_evento: string;
  usomod: Generated<number>;
  usunvo: Generated<number>;
}

export interface Tbexistcortes {
  corte: number;
  envia: number;
  exinicial: number;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  producto: number;
  usumod: number;
  usunvo: number;
}

export interface Tbfacturas {
  cancel: number;
  cliente: number;
  condpago: string;
  ctadep: string;
  desctot: Decimal;
  envia: number;
  factura: number;
  fecfac: Date;
  fecmod: Date;
  fecnvo: Date;
  fecpago: Date;
  fecvence: Date;
  formapago: number;
  global: number;
  ieps: Decimal;
  iva: Decimal;
  lugarexp: string;
  metodopago: string;
  moneda: number;
  obsvta: string;
  saldo: Decimal;
  serie: string;
  subtotal: Decimal;
  tc: Decimal;
  timbre: number;
  /**
   * Indica si es de un ticket o una mensualidad
   */
  tipo: string;
  tipocompr: string;
  /**
   * Indica el ID en caso de ticket o idmens
   */
  tipoid: number;
  total: Decimal;
  usocfdi: string;
  usumod: number;
  usunvo: number;
}

export interface Tbformaspago {
  c_formapago: string;
  c_moneda: string;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  fp: number;
  id: Generated<number>;
  nomfp: string;
  usumod: number;
  usunvo: number;
}

export interface Tbfotosrutinas {
  activo: number;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  foto: string | null;
  id: Generated<number>;
  rutina: number;
  usumod: number;
  usunvo: number;
}

export interface Tbgastos {
  cheque: number;
  concepto: number;
  corte: number;
  dedonde: number;
  envia: number;
  fecha: Date;
  fecmod: Date;
  fecnvo: Date;
  fp: number;
  id: Generated<number>;
  idmov: number;
  importe: Decimal;
  motivo: string;
  obs: string | null;
  proveedor: number;
  tipgasto: number;
  usumod: number;
  usunvo: number;
}

export interface Tbgruposprod {
  cnt: Decimal;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  producto: number;
  subproducto: number;
  usumod: number;
  usunvo: number;
}

export interface Tbhorarios {
  clase: number;
  do: number;
  duracion: number;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  hora: number;
  horario: number;
  id: Generated<number>;
  instructor: number;
  ju: number;
  lu: number;
  ma: number;
  mi: number;
  sa: number;
  usumod: number;
  usunvo: number;
  vi: number;
}

export interface Tbhorariosdet {
  clase: number;
  dia: number;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  hora: number;
  horario: number;
  hrant: number;
  hrdes: number;
  id: Generated<number>;
  instructor: number;
  usumod: number;
  usunvo: number;
}

export interface Tbhorariossocio {
  clase: number;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  horario: number;
  id: Generated<number>;
  socio: number;
  usumod: number;
  usunvo: number;
}

export interface Tbhuellas {
  dedo: number;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  huella: string | null;
  id: Generated<number>;
  socio: number;
  usumod: number;
  usunvo: number;
}

export interface Tbingresos {
  cancelado: number;
  corte: number;
  envia: number;
  fecha: Date;
  fecmod: Date;
  fecnvo: Date;
  fp: number;
  id: Generated<number>;
  iding: number;
  idmens: number;
  importe: Decimal;
  referencia: string;
  socio: number;
  ticket: number;
  usuario: number;
  usumod: number;
  usunvo: number;
}

export interface Tbinstructores {
  activo: number;
  cel: string;
  correo: string;
  envia: number;
  especialidad: string;
  fecmod: Date;
  fecnvo: Date;
  foto: string;
  fotostr: string | null;
  id: Generated<number>;
  instructor: number;
  nominstructor: string;
  tel: string;
  usumod: number;
  usunvo: number;
}

export interface Tblogsocio {
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  log: string;
  socio: number;
  usuario: number;
  usumod: number;
  usunvo: number;
}

export interface Tbmedidas {
  brazo: Decimal;
  cadera: Decimal;
  cintura: Decimal;
  dias: number;
  envia: number;
  fechamed: Date;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  mmbrazo: Decimal;
  mmcadera: Decimal;
  mmcintura: Decimal;
  mmmuslo: Decimal;
  mmpantorrilla: Decimal;
  mmpecho: Decimal;
  mmpeso: Decimal;
  mmporgrasa: Decimal;
  muslo: Decimal;
  pantorrilla: Decimal;
  pecho: Decimal;
  peso: Decimal;
  porgrasa: Decimal;
  socio: number;
  usumod: number;
  usunvo: number;
}

export interface Tbmensualidades {
  autcan: number;
  cancelado: number;
  descrip: string;
  descuento: Decimal;
  envia: number;
  factura: string;
  fecha: Date;
  fecmod: Date;
  fecnvo: Date;
  fecpago: Date;
  id: Generated<number>;
  idmens: number;
  importe: Decimal;
  inscrip: number;
  modopago: number;
  motivo: string;
  notas: string | null;
  pagado: number;
  saldo: Decimal;
  socio: number;
  total: Decimal;
  usumod: number;
  usunvo: number;
}

export interface Tbmodospago {
  cadadias: number;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  modopago: number;
  nommodopago: string;
  usumod: number;
  usunvo: number;
}

export interface Tbmotivossal {
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  motivo: number;
  nommotivo: string;
  usumod: number;
  usunvo: number;
}

export interface Tbnivelrutina {
  activo: number;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  nivel: number;
  nomnivel: string;
  usumod: number;
  usunvo: number;
}

export interface Tbnotificaciones {
  descripcion: string;
  envia: Generated<number>;
  estatus: number;
  fecmod: Date | null;
  fecnvo: Date;
  idnotificacion: Generated<number>;
  usomod: Generated<number>;
  usunvo: number;
  vigencia: Date;
}

export interface Tbocompra {
  descrip: string;
  entpar: number;
  envia: number;
  estatus: number;
  fecha: Date;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  iva: Decimal;
  obs: string | null;
  oc: number;
  proveedor: number;
  subtotal: Decimal;
  tipoc: number;
  total: Decimal;
  usumod: number;
  usunvo: number;
}

export interface Tbpagos {
  bcoemisor: number;
  bcoordenante: number;
  cadenapago: string;
  cancel: number;
  certificadopago: string;
  claveprodserv: string;
  cliente: number;
  cnt: number;
  confirmacion: string;
  ctabeneficiario: string;
  ctaordenante: string;
  cveunidad: string;
  envia: number;
  fechapago: Date;
  fecmod: Date;
  fecnvo: Date;
  formapago: number;
  importe: Decimal;
  lugarexp: string;
  metodopago: string;
  moneda: number;
  monto: Decimal;
  numop: string;
  pago: number;
  sellopago: string;
  serie: string;
  subtotal: Decimal;
  timbre: number;
  tipocambio: Decimal;
  tipocomprobante: string;
  total: Decimal;
  tpcadenapago: string;
  usocfdi: string;
  usumod: number;
  usunvo: number;
  valorunitario: Decimal;
}

export interface Tbparametros {
  accesos: number;
  acciondessoc: number;
  accionreacsoc: number;
  activacumple: number;
  aplicadescdias: number;
  baud: number;
  /**
   * 1 = para buscar comentarios WEB
   */
  buscacomentarios: Generated<number>;
  cadena: string;
  cajoncom: number;
  cajonprint: number;
  calle: string;
  cambiodp: number;
  ciudad: string;
  clavesuc: Generated<string | null>;
  claveunidadmens: string;
  cntfaltas: number;
  colonia: string;
  comandoopen: string;
  conceptofac: string;
  conssocio: number;
  copias: number;
  cp: string;
  cuenta: string;
  "cuentadueño": string;
  cveprodmens: string;
  cveprodserv: string;
  demo: number;
  dessocaut: number;
  diaspaqvisvence: number;
  dir1: string;
  dir2: string;
  dir3: string;
  emcancelamens: number;
  emcorte: number;
  empresa: string;
  envia: number;
  esp: number;
  estado: string;
  eti1: string;
  eti10: string;
  eti2: string;
  eti3: string;
  eti4: string;
  eti5: string;
  eti6: string;
  eti7: string;
  eti8: string;
  eti9: string;
  fcd: string;
  fechasis: Date;
  fecmod: Date;
  fecnvo: Date;
  filecer: string;
  filekey: string;
  firmacorreo: string | null;
  formapago: number;
  fsd: string;
  /**
   * 1 =no genera las mensualidades automaticamente al entrar a ventas
   */
  genmensaut: number;
  id: Generated<number>;
  imagencumple: string;
  imgpub: string;
  impcopia: number;
  impticket: number;
  inicaja: Decimal;
  interior: string;
  iva: number;
  ivainc: number;
  ivaincmens: number;
  keylic: string;
  leyenda: string;
  logocte: string;
  lugarexp: string;
  metodopago: string;
  metodoreg: number;
  mincw: Generated<number | null>;
  minutos: number;
  "nombredueño": string;
  notfaltas: number;
  numero: string;
  nxtfac: number;
  pagospar: number;
  paqvisacum: number;
  paqvisvence: number;
  prhora: Decimal;
  psw: string;
  pswcfdi: string;
  puerto: number;
  puertosmtp: number;
  razon: string;
  redcent: number;
  regimenfis: string;
  regimenfiscal: string;
  reqaut: number;
  rfc: string;
  segesp: number;
  serie: string;
  serversmtp: string;
  sonido: number;
  sonidomsj: string;
  sucursal: number;
  tels: string;
  textocumple: string;
  tipocaja: number;
  tipocompr: string;
  tit1: string;
  tit2: string;
  tit3: string;
  tit4: string;
  tit5: string;
  tit6: string;
  tit7: string;
  tit8: string;
  ultact: Date;
  user: string;
  usocfdi: string;
  usumod: number;
  usunvo: number;
  vissuc: Generated<number | null>;
  vissucacc: Generated<number | null>;
  vissucdias: Generated<number | null>;
  vissucdo: Generated<number | null>;
  vissucju: Generated<number | null>;
  vissuclu: Generated<number | null>;
  vissucma: Generated<number | null>;
  vissucmi: Generated<number | null>;
  vissucsa: Generated<number | null>;
  vissucvalacc: Generated<number | null>;
  vissucvalvig: Generated<number | null>;
  vissucvi: Generated<number | null>;
}

export interface Tbparamsat {
  cantp: number;
  claveprodpago: string;
  cveunidadp: string;
  descripp: string;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  importep: Decimal;
  metodopagop: string;
  monedapago: string;
  subtotal: Decimal;
  tipocomprobantepago: string;
  tiporelacion: string;
  total: Decimal;
  usocfdipago: string;
  usumod: number;
  usunvo: number;
  valorunitariop: Decimal;
}

export interface Tbparterutina {
  activo: number;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  nomparte: string;
  parte: number;
  usumod: number;
  usunvo: number;
}

export interface Tbperfiles {
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  nombre: string;
  perfil: number;
  usumod: number;
  usunvo: number;
}

export interface Tbprodcancel {
  autorizo: number;
  envia: number;
  feccan: Date;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  idcan: number;
  motivo: string;
  producto: number;
  usuario: number;
  usumod: number;
  usunvo: number;
}

export interface Tbproductos {
  activo: number;
  almacen: number;
  categoria: number;
  codigob: string;
  combo: number;
  costo: Decimal;
  cveprodserv: string;
  enpantalla: number;
  envia: number;
  exinicorte: Decimal;
  existencia: Decimal;
  fecmod: Date;
  fecnvo: Date;
  foto: string;
  geniva: number;
  id: Generated<number>;
  maximo: Decimal;
  minimo: Decimal;
  nomproducto: string;
  pantalla: number;
  paqvisitas: number;
  plazocred: number;
  porcieps: Decimal;
  posicion: number;
  producto: number;
  unidad: number;
  usumod: number;
  usunvo: number;
  venta: Decimal;
  visitas: number;
}

export interface Tbprogramas {
  envia: number;
  formet: string;
  id: Generated<number>;
  menu: number;
  nombre: string;
  opcion: number;
  runf: number;
  subopcion: number;
}

export interface Tbproveedores {
  activo: number;
  contacto: string;
  correo: string;
  direccion: string | null;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  nomproveedor: string;
  proveedor: number;
  rfc: string;
  tel1: string;
  tel2: string;
  usumod: number;
  usunvo: number;
}

export interface Tbpublicidad {
  activo: number;
  descripcion: string | null;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  idpublicidad: Generated<number>;
  logo: Buffer | null;
  nombreimagen: string;
  tipo: number;
  tipoimagen: string;
  titulo: string;
  usumod: number;
  usunvo: number;
}

export interface Tbreportes {
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  nomreporte: string;
  reporte: number;
  usumod: number;
  usunvo: number;
}

export interface Tbrescortes {
  clave: number;
  corte: number;
  descrip: string;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  importe: Decimal;
  parte: number;
  usumod: number;
  usunvo: number;
}

export interface Tbresenia {
  envia: number;
  estatus: number | null;
  fecha: Date | null;
  fecmod: Date;
  fecnvo: Date;
  id_resenia: Generated<number>;
  idsocio: number | null;
  resenia: string | null;
  usumod: number;
  usunvo: number;
}

export interface Tbrutinas {
  activo: number;
  comentarios: string;
  descanso: string;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  imagen: string;
  nivel: number;
  nomrutina: string;
  parte: number;
  peso: string;
  repeticiones: string;
  rutina: number;
  series: string;
  tipo: number;
  usumod: number;
  usunvo: number;
}

export interface Tbsalidasalm {
  envia: number;
  fecha: Date;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  idsal: number;
  motivo: number;
  obs: string | null;
  responsable: string;
  total: Decimal;
  usumod: number;
  usunvo: number;
}

export interface Tbsalidasefec {
  corte: number;
  envia: number;
  fecha: Date;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  idmov: number;
  importe: Decimal;
  motivo: string;
  obs: string | null;
  usumod: number;
  usunvo: number;
}

export interface Tbsocios {
  activo: number;
  becado: number;
  campo1: string;
  campo10: string;
  campo2: string;
  campo3: string;
  campo4: string;
  campo5: string;
  campo6: string;
  campo7: string;
  campo8: string;
  campo9: string;
  clases: string;
  correo: string;
  "cumpleaños": Date;
  descpo: Decimal;
  diapago: Date;
  direccion: string;
  envia: number;
  fcalle: string;
  fciudad: string;
  fcolonia: string;
  fcp: string;
  fecmod: Date;
  fecnvo: Date;
  fecvencevis: Date;
  festado: string;
  finterior: string;
  fnumero: string;
  foto: string;
  fotostr: string | null;
  id: Generated<number>;
  importepago: Decimal;
  modopago: number;
  nivel: number;
  nomsocio: string;
  obs: string | null;
  razonsocial: string;
  rfc: string;
  sexo: number;
  socio: number;
  tel1: string;
  tel2: string;
  usumod: number;
  usunvo: number;
  visitasdisp: number;
  vissucacc: number | null;
  visvig: Date | null;
}

export interface Tbsociosfotos {
  activo: number;
  envia: number;
  foto: string;
  fotostr: string | null;
  id: Generated<number>;
  socio: number;
}

export interface Tbtickets {
  autcan: number;
  cancelado: number;
  corte: number;
  credito: number;
  descuento: Decimal;
  envia: number;
  factura: string;
  fecha: Date;
  fechacred: Date | null;
  fecmod: Date;
  fecnvo: Date;
  fecpag: Date;
  id: Generated<number>;
  ieps: Decimal;
  impdesc: Decimal;
  importe: Decimal;
  iva: Decimal;
  motivo: string;
  notas: string | null;
  pagado: number;
  plazocred: number | null;
  saldo: Decimal;
  socio: number;
  ticket: number;
  total: Decimal;
  usuario: number;
  usumod: number;
  usunvo: number;
}

export interface Tbtipodieta {
  activo: number;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  nomtipo: string;
  tipo: number;
  usumod: number;
  usunvo: number;
}

export interface Tbtiporutina {
  activo: number;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  nomtipo: string;
  tipo: number;
  usumod: number;
  usunvo: number;
}

export interface Tbunidadesmed {
  claveunidad: string;
  envia: number;
  fecmod: Date;
  fecnvo: Date;
  id: Generated<number>;
  nomunidad: string;
  unidad: number;
  usumod: number;
  usunvo: number;
}

export interface Tbusuarios {
  activo: number;
  admin: number;
  altasocios: number;
  aplicadesc: number;
  bajasocios: number;
  becas: number;
  cajero: number;
  cambioprecio: number;
  cambiosuscrip: number;
  cancela: number;
  cancelamens: number;
  clave: string;
  cobranza: number;
  email: string;
  enuso: number;
  envia: number;
  estacion: string;
  facturar: number;
  fechaest: Date;
  fecmod: Date;
  fecnvo: Date;
  foto: string;
  id: Generated<number>;
  moddp: number;
  modis: number;
  nombre: string;
  nxting: number;
  nxtmens: number;
  nxtticket: number;
  perfil: number;
  psw: string;
  puesto: string;
  salefe: number;
  salprod: number;
  telefono: string;
  usuario: number;
  usumod: number;
  usunvo: number;
  vtasdia: number;
}

export interface DB {
  tbacc: Tbacc;
  tbaccclases: Tbaccclases;
  tbaccesos: Tbaccesos;
  tbaccperfiles: Tbaccperfiles;
  tbagenda: Tbagenda;
  tbapertura: Tbapertura;
  tbaperturas: Tbaperturas;
  tbasistencia: Tbasistencia;
  tbbancos: Tbbancos;
  tbbdkpc: Tbbdkpc;
  tbbloqueados: Tbbloqueados;
  tbc_claveprodser: TbcClaveprodser;
  tbc_claveunidad: TbcClaveunidad;
  tbc_codigopostal: TbcCodigopostal;
  tbc_formapago: TbcFormapago;
  tbc_metodopago: TbcMetodopago;
  tbc_moneda: TbcMoneda;
  tbc_regimenfiscal: TbcRegimenfiscal;
  tbc_tasaocuota: TbcTasaocuota;
  tbc_tipocadenapago: TbcTipocadenapago;
  tbc_tipocomprobante: TbcTipocomprobante;
  tbc_tiporelacion: TbcTiporelacion;
  tbc_usocfdi: TbcUsocfdi;
  tbcategorias: Tbcategorias;
  tbcfdis: Tbcfdis;
  tbclases: Tbclases;
  tbcobranza: Tbcobranza;
  tbconceptos: Tbconceptos;
  tbconsumodieta: Tbconsumodieta;
  tbcortes: Tbcortes;
  tbdescuentos: Tbdescuentos;
  tbdetcortes: Tbdetcortes;
  tbdetdietas: Tbdetdietas;
  tbdetdietasocio: Tbdetdietasocio;
  tbdetentradasalm: Tbdetentradasalm;
  tbdetfacs: Tbdetfacs;
  tbdetoc: Tbdetoc;
  tbdetrutinasocio: Tbdetrutinasocio;
  tbdetsalidasalm: Tbdetsalidasalm;
  tbdettickets: Tbdettickets;
  tbdietas: Tbdietas;
  tbentradasalm: Tbentradasalm;
  tbestatus: Tbestatus;
  tbeventos: Tbeventos;
  tbexistcortes: Tbexistcortes;
  tbfacturas: Tbfacturas;
  tbformaspago: Tbformaspago;
  tbfotosrutinas: Tbfotosrutinas;
  tbgastos: Tbgastos;
  tbgruposprod: Tbgruposprod;
  tbhorarios: Tbhorarios;
  tbhorariosdet: Tbhorariosdet;
  tbhorariossocio: Tbhorariossocio;
  tbhuellas: Tbhuellas;
  tbingresos: Tbingresos;
  tbinstructores: Tbinstructores;
  tblogsocio: Tblogsocio;
  tbmedidas: Tbmedidas;
  tbmensualidades: Tbmensualidades;
  tbmodospago: Tbmodospago;
  tbmotivossal: Tbmotivossal;
  tbnivelrutina: Tbnivelrutina;
  tbnotificaciones: Tbnotificaciones;
  tbocompra: Tbocompra;
  tbpagos: Tbpagos;
  tbparametros: Tbparametros;
  tbparamsat: Tbparamsat;
  tbparterutina: Tbparterutina;
  tbperfiles: Tbperfiles;
  tbprodcancel: Tbprodcancel;
  tbproductos: Tbproductos;
  tbprogramas: Tbprogramas;
  tbproveedores: Tbproveedores;
  tbpublicidad: Tbpublicidad;
  tbreportes: Tbreportes;
  tbrescortes: Tbrescortes;
  tbresenia: Tbresenia;
  tbrutinas: Tbrutinas;
  tbsalidasalm: Tbsalidasalm;
  tbsalidasefec: Tbsalidasefec;
  tbsocios: Tbsocios;
  tbsociosfotos: Tbsociosfotos;
  tbtickets: Tbtickets;
  tbtipodieta: Tbtipodieta;
  tbtiporutina: Tbtiporutina;
  tbunidadesmed: Tbunidadesmed;
  tbusuarios: Tbusuarios;
}
